---
# tasks file for common
- include_vars: "{{ansible_distribution}}.yml"

- name: Obtain repository config
  set_fact:
    mongodb_repository_data: "{{mongodb_repository_config[mongodb_major_minor_version]}}"

- name: Add APT key
  apt_key: keyserver=keyserver.ubuntu.com id="{{mongodb_repository_data.key}}"

- name: Add APT repository
  apt_repository: repo="{{mongodb_repository_data.repository}}" update_cache=yes

- name: Install MongoDB package
  apt: name=mongodb-org state=present force=yes

- name: create a directory if it doesn't exist
  # become: yes
  file:
    path: /data/db
    state: directory
    mode: 0755

- name: enable service mongod
  systemd:
    name: mongod
    enabled: yes

- name: make sure mongod is running
  systemd:
    state: started
    name: mongod

# - name: Install additional packages
#   apt: name={{item}}
#   with_items: "{{mongodb_additional_packages}}"
